# Site settings
title: Kais Mathe-Seite
tagline: 'Proofs using baby steps'
url: 'https://kmorgen1.github.io/kais-mathe-seite/' # The base hostname & protocol for your site. Use it if you need absolute URL's. This should NOT end in a `/` character
permalink: /posts/:title/
author: author
socialimg: ''

exclude: [.scss, README.md, node_modules, gruntfile.js, package.json]
future: true
